import Button from "@/Components/UI/Button/Button";
import { BiLineChart } from "react-icons/bi";
import { BsBoxSeam } from "react-icons/bs";
import { FaArrowTrendUp } from "react-icons/fa6";
import { FiCheckCircle, FiCreditCard, FiTruck } from "react-icons/fi";
import { GiNetworkBars } from "react-icons/gi";
import { GoCalendar } from "react-icons/go";
import { LuUserRound, LuUsers, LuWallet } from "react-icons/lu";
import { MdOutlineAttachMoney, MdOutlineTrendingUp } from "react-icons/md";
import { RxCrossCircled } from "react-icons/rx";
import { TbClock } from "react-icons/tb";

export const ReportData = {
  overview: [
    {
      id: 1,
      title: "Appointment Reports",
      description: "Track appointment metrics, trends, and patient attendance",
      name: ["Total Appointments", "Completion Rate", "No-Show Rate"],
      value: ["1,248", "70.2%", "6.8%"],
      icon: <GoCalendar />,
      btn: <Button variant="secondary" text="View Report" className="w-full" />,
    },
    {
      id: 2,
      title: "Financial Reports",
      description: "Track revenue, expenses, and financial performance",
      name: ["Total Revenue", "Net Profit", "Growth"],
      value: ["$128,450", "$41,125", "+12.8%"],
      icon: <FaArrowTrendUp />,
      btn: <Button variant="secondary" text="View Report" className="w-full" />,
    },
    {
      id: 3,
      title: "Patient Visit Reports",
      description: "Analyze patient visits, demographics, and health trends",
      name: ["Total Visits", "New Patients", "Avg. Duration"],
      value: ["3,842", "428", "32 min"],
      icon: <LuUsers />,
      btn: <Button variant="secondary" text="View Report" className="w-full" />,
    },
    {
      id: 4,
      title: "Inventory Reports",
      description: "Track inventory levels, usage, and supply chain metrics",
      name: ["Total Items", "Low Stock", "Inventory Value"],
      value: ["1,245", "32", "$248,320"],
      icon: <BsBoxSeam />,
      btn: <Button variant="secondary" text="View Report" className="w-full" />,
    },
    {
      id: 5,
      title: "Staff Performance",
      description: "Evaluate staff productivity, attendance, and performance",
      name: ["Staff Count", "Avg. Attendance", "Productivity"],
      value: ["48", "92.5%", "87.3%"],
      icon: <GiNetworkBars />,
      btn: (
        <Button
          variant="primary"
          text="Coming Soon"
          className="w-full border border-gray-300"
        />
      ),
    },
    {
      id: 6,
      title: "Custom Reports",
      description:
        "Create customized reports with specific metrics and filters",
      name: ["Saved Reports", "Templates", "Export Options"],
      value: ["5", "12", "PDF, CSV, Excel"],
      icon: <BiLineChart />,
      btn: (
        <Button
          variant="primary"
          text="Coming Soon"
          className="w-full border border-gray-300"
        />
      ),
    },
  ],
  appointmentReport: {
    card: [
      {
        id: 1,
        title: "Total Appointments",
        value: "1,248",
        text: "+12.5% from last month",
        icon: <GoCalendar size={24} />,
        progressValue: 70,
        progressColor: "#171717",
      },
      {
        id: 2,
        title: "Completed",

        value: "876",
        text: "70.2% completion rate",
        icon: <FiCheckCircle size={24} />,
        progressValue: 60,
        progressColor: "#22C55E",
      },
      {
        id: 3,
        title: "Canceled",

        value: "187",
        text: "15% cancellation rate",
        icon: <RxCrossCircled size={24} />,
        progressValue: 30,
        progressColor: "#EF4444",
      },
      {
        id: 4,
        title: "No-Shows",

        value: "85",
        text: "6.8% no-show rate",
        icon: <TbClock size={24} />,
        progressValue: 20,
        progressColor: "#F59E0B",
      },
    ],
    overview: [
      {
        id: 1,
        title: "Department-wise Appointments",
        description: "Distribution of appointments by department",
        name: ["Canceled", "Completed", "Not Show", "Scheduled"],
        overviewPieChart: [
          { name: "Scheduled", value: 38, color: "#10B981" },
          { name: "Completed", value: 45, color: "#2563EB" },
          { name: "Canceled", value: 32, color: "#FFBB28" },
          { name: "Not Show", value: 28, color: "#FF8042" },
        ],
        overviewBarChart: [
          { name: "Orthopedics", appointment: 225 },
          { name: "Neurology", appointment: 187 },
          { name: "Oncology", appointment: 201 },
          { name: "Dermatology", appointment: 224 },
          { name: "Psychiatry", appointment: 163 },
          { name: "Ophthalmology", appointment: 228 },
        ],
        recentAppointment: [
          {
            patient: "Emma Thompson",
            doctor: "Dr. Smith",
            date: "Today",
            time: "10:00 AM",
            service: "General Checkup",
            status: "Completed",
          },
          {
            patient: "James Wilson",
            doctor: "Dr. Asif",
            date: "Yesterday",
            time: "2:30 PM",
            service: "Consultation",
            status: "Canceled",
          },
          {
            patient: "Liam Anderson",
            doctor: "Dr. Rakib",
            date: "Last Week",
            time: "11:00 AM",
            service: "Follow-up",
            status: "Not Show",
          },
          {
            patient: "Olivia Taylor",
            doctor: "Dr. Sarah",
            date: "Last Month",
            time: "1:00 PM",
            service: "Skin Checkup",
            status: "Scheduled",
          },
          {
            patient: "Noah Garcia",
            doctor: "Dr. Adams",
            date: "Today",
            time: "3:00 PM",
            service: "Therapy Session",
            status: "Completed",
          },
          {
            patient: "Ava Rodriguez",
            doctor: "Dr. Lee",
            date: "Yesterday",
            time: "9:00 AM",
            service: "ECG",
            status: "Completed",
          },
          {
            patient: "William Lee",
            doctor: "Dr. Brown",
            date: "Last Week",
            time: "10:30 AM",
            service: "Vaccination",
            status: "Scheduled",
          },
          {
            patient: "Isabella Hernandez",
            doctor: "Dr. Chen",
            date: "Today",
            time: "4:15 PM",
            service: "Eye Exam",
            status: "Canceled",
          },
          {
            patient: "Mason Lopez",
            doctor: "Dr. Asif",
            date: "Last Month",
            time: "2:00 PM",
            service: "Consultation",
            status: "Completed",
          },
          {
            patient: "Mason Lopez",
            doctor: "Dr. Smith",
            date: "Yesterday",
            time: "11:45 AM",
            service: "X-ray",
            status: "Not Show",
          },
        ],
        appointmentTrends: [
          { name: "Jan", completed: 95, canceled: 15, totalAppointment: 120 },
          {
            name: "Fev",
            completed: 110,
            canceled: 18,
            totalAppointment: 135.25,
          },
          { name: "Mar", completed: 125, canceled: 15, totalAppointment: 150 },
          { name: "Apr", completed: 115, canceled: 20, totalAppointment: 145 },
          { name: "May", completed: 130, canceled: 22, totalAppointment: 160 },
          { name: "Jun", completed: 145, canceled: 20, totalAppointment: 175 },
          { name: "Jul", completed: 155, canceled: 25, totalAppointment: 190 },
          { name: "Aug", completed: 150, canceled: 20, totalAppointment: 180 },
          { name: "Sep", completed: 160, canceled: 25, totalAppointment: 195 },
          { name: "Oct", completed: 175, canceled: 25, totalAppointment: 210 },
          { name: "Nov", completed: 185, canceled: 30, totalAppointment: 225 },
          { name: "Dec", completed: 200, canceled: 30, totalAppointment: 240 },
        ],
        weeklyDistribution: [
          { name: "Mon", appointments: 45 },
          { name: "Tue", appointments: 58 },
          { name: "Wed", appointments: 48 },
          { name: "Thu", appointments: 50 },
          { name: "Fri", appointments: 40 },
          { name: "Sat", appointments: 35 },
          { name: "Sun", appointments: 15 },
        ],
        hourlyDistribution: [
          { name: "8 am", appointment: 15 },
          { name: "9 am", appointment: 25 },
          { name: "10am", appointment: 30 },
          { name: "11 am", appointment: 28 },
          { name: "12 pm", appointment: 20 },
          { name: "1 pm", appointment: 18 },
          { name: "2 pm", appointment: 25 },
          { name: "3 pm", appointment: 30 },
          { name: "4 pm", appointment: 25 },
          { name: "5 pm", appointment: 15 },
        ],
        appointmentByDoctor: [
          {
            department: "Cardiology",
            doctor: "Dr. Smith",
            totalAppointments: 245,
            completed: 198,
            canceled: 32,
            notShow: 15,
          },
          {
            department: "Neurology",
            doctor: "Dr. Asif",
            totalAppointments: 187,
            completed: 156,
            canceled: 21,
            notShow: 10,
          },
          {
            department: "Orthopedics",
            doctor: "Dr. Johnson",
            totalAppointments: 163,
            completed: 129,
            canceled: 22,
            notShow: 10,
          },
          {
            department: "Dermatology",
            doctor: "Dr. Rakib",
            totalAppointments: 210,
            completed: 172,
            canceled: 19,
            notShow: 10,
          },
          {
            department: "Pediatrics",
            doctor: "Dr. Emma Thompson",
            totalAppointments: 224,
            completed: 183,
            canceled: 29,
            notShow: 12,
          },
        ],
        doctorPerformance: [
          {
            name: "Dr. Smith",
            completed: 198,
            canceled: 32,
            notShows: 15,
          },
          {
            name: "Dr. Johnson",
            completed: 156,
            canceled: 21,
            notShows: 10,
          },
          {
            name: "Dr. Williams",
            completed: 129,
            canceled: 24,
            notShows: 10,
          },
          {
            name: "Dr. Brown",
            completed: 172,
            canceled: 19,
            notShows: 10,
          },
          {
            name: "Dr. Jones",
            completed: 183,
            canceled: 29,
            notShows: 12,
          },
        ],
        serviceType: [
          {
            name: "Jan",
            generalCheckup: 45,
            Cardiology: 30,
            Orthopedics: 25,
            Pediatrics: 20,
            Dermatology: 35,
          },
          {
            name: "Fev",
            generalCheckup: 50,
            Cardiology: 35,
            Orthopedics: 28,
            Pediatrics: 22,
            Dermatology: 38,
          },
          {
            name: "Mar",
            generalCheckup: 55,
            Cardiology: 38,
            Orthopedics: 30,
            Pediatrics: 25,
            Dermatology: 40,
          },
          {
            name: "Apr",
            generalCheckup: 52,
            Cardiology: 36,
            Orthopedics: 29,
            Pediatrics: 24,
            Dermatology: 39,
          },
          {
            name: "May",
            generalCheckup: 58,
            Cardiology: 40,
            Orthopedics: 32,
            Pediatrics: 27,
            Dermatology: 42,
          },
          {
            name: "Jun",
            generalCheckup: 62,
            Cardiology: 42,
            Orthopedics: 34,
            Pediatrics: 29,
            Dermatology: 45,
          },
        ],
        servicePopularity: [
          {
            service: "Dental Cleaning",
            department: "Dentistry",
            appointments: 312,
            avgDuration: 30,
          },
          {
            service: "Vision Checkup",
            department: "Ophthalmology",
            appointments: 187,
            avgDuration: 45,
          },
          {
            service: "General Consultation",
            department: "Internal Medicine",
            appointments: 156,
            avgDuration: 25,
          },
          {
            service: "Physical Therapy",
            department: "Rehabilitation",
            appointments: 143,
            avgDuration: 40,
          },
          {
            service: "Vaccination",
            department: "Pediatrics",
            appointments: 201,
            avgDuration: 35,
          },
        ],
      },
    ],
  },
  financialReport: {
    card: [
      {
        id: 1,
        title: "Total Revenue",
        value: "128,450",
        text: "+18.2% from last month",
        icon: <MdOutlineAttachMoney size={24} />,
        progressValue: 70,
        progressColor: "#171717",
      },
      {
        id: 2,
        title: "Total Expenses",
        value: "87,325",
        text: "+5.4% from last month",
        icon: <LuWallet size={24} />,
        progressValue: 60,
        progressColor: "#22C55E",
      },
      {
        id: 3,
        title: "Net Profit",
        value: "41,125",
        text: "+12.8% from last month",
        icon: <MdOutlineTrendingUp size={24} />,
        progressValue: 30,
        progressColor: "#EF4444",
      },
      {
        id: 4,
        title: "Outstanding Payments",
        value: "23,540",
        text: "+3.2% from last month",
        icon: <FiCreditCard size={24} />,
        progressValue: 20,
        progressColor: "#F59E0B",
      },
    ],
    overview: [
      {
        id: 1,
        title: "Financial Overview",
        description:
          "Monthly financial statistics including revenue, expenses, and profit.",
        revenueExpenses: [
          {
            name: "Jan",
            profit: 24050,
            expenses: 78250,
            revenue: 102300,
          },
          {
            name: "Fev",
            profit: 23800,
            expenses: 78350,
            revenue: 100150,
          },
          {
            name: "Mar",
            profit: 25800,
            expenses: 82850,
            revenue: 108650,
          },
          {
            name: "Apr",
            profit: 45125,
            expenses: 87325,
            revenue: 128450,
          },
          {
            name: "May",
            profit: 33125,
            expenses: 83200,
            revenue: 116700,
          },
          {
            name: "June",
            profit: 36400,
            expenses: 85100,
            revenue: 121500,
          },
        ],
        revenueDepartmentPieChart: [
          { name: "Orthopedics", value: 22, color: "#10B981" },
          { name: "Cardiology", value: 27, color: "#2563EB" },
          { name: "Pediatrics", value: 12, color: "#FF8042" },
          { name: "Neurology", value: 14, color: "#FFBB28" },
          { name: "Dermatology", value: 10, color: "#8884D8" },
          { name: "Other", value: 14, color: "#82CA9D" },
        ],
        financialSummary: [
          {
            month: "December 2022",
            revenue: 112300,
            expenses: 60000,
            profit: 60000,
            margin: "34.1%",
            growth: 0,
          },
          {
            month: "January 2023",
            revenue: 100150,
            expenses: 78250,
            profit: 45125,
            margin: "34.1%",
            growth: -10.85,
          },
          {
            month: "February 2023",
            revenue: 108650,
            expenses: 76350,
            profit: 45125,
            margin: "34.1%",
            growth: 8.49,
          },
          {
            month: "March 2023",
            revenue: 128450,
            expenses: 82885,
            profit: 45125,
            margin: "34.1%",
            growth: 18.22,
          },
          {
            month: "April 2023",
            revenue: 160450,
            expenses: 45325,
            profit: 62125,
            margin: "34.1%",
            growth: 24.91,
          },
        ],
        revenueTrends: [
          {
            name: "Jan",
            consultations: 32500,
            procedures: 25800,
            tests: 18200,
            surgeries: 15400,
            therapy: 10400,
          },
          {
            name: "Fev",
            consultations: 31200,
            procedures: 24900,
            tests: 17800,
            surgeries: 16100,
            therapy: 10150,
          },
          {
            name: "Mar",
            consultations: 33800,
            procedures: 27200,
            tests: 19100,
            surgeries: 17500,
            therapy: 11050,
          },
          {
            name: "Apr",
            consultations: 38500,
            procedures: 32100,
            tests: 22800,
            surgeries: 21520,
            therapy: 13550,
          },
          {
            name: "May",
            consultations: 32200,
            procedures: 29800,
            tests: 21100,
            surgeries: 19200,
            therapy: 11400,
          },
          {
            name: "Jun",
            consultations: 35200,
            procedures: 30500,
            tests: 21800,
            surgeries: 19200,
            therapy: 11400,
          },
        ],
        paymentMethod: [
          { name: "Insurance", value: 68258, fill: "#8884d8" },
          { name: "Credit Card", value: 32158, fill: "#82ca9d" },
          { name: "Cash", value: 15750, fill: "#ffc658" },
          { name: "Bank Transfer", value: 8450, fill: "#ff8042" },
          { name: "Other", value: 3850, fill: "#d0ed57" },
        ],
        revenueSources: [
          {
            Service: "Cardiology Consultations",
            Department: "Cardiology",
            Revenue: 28450,
          },
          {
            Service: "Orthopedic Surgeries",
            Department: "Orthopedics",
            Revenue: 32500,
          },
          {
            Service: "Pediatric Checkups",
            Department: "Pediatrics",
            Revenue: 14500,
          },
          {
            Service: "Neurology Tests",
            Department: "Neurology",
            Revenue: 17800,
          },
          {
            Service: "Dermatology Treatments",
            Department: "Dermatology",
            Revenue: 12000,
          },
        ],
        expenseBreakdown: [
          {
            name: "Jan",
            salaries: 45,
            supplies: 30,
            maintenance: 25,
            utilities: 20,
            administrative: 35,
          },
          {
            name: "Feb",
            salaries: 48,
            supplies: 28,
            maintenance: 22,
            utilities: 18,
            administrative: 32,
          },
          {
            name: "Mar",
            salaries: 50,
            supplies: 32,
            maintenance: 27,
            utilities: 19,
            administrative: 34,
          },
          {
            name: "Apr",
            salaries: 47,
            supplies: 31,
            maintenance: 24,
            utilities: 21,
            administrative: 33,
          },
          {
            name: "May",
            salaries: 49,
            supplies: 29,
            maintenance: 26,
            utilities: 20,
            administrative: 36,
          },
          {
            name: "Jun",
            salaries: 46,
            supplies: 30,
            maintenance: 23,
            utilities: 22,
            administrative: 31,
          },
        ],
        expenseDepartment: [
          { name: "Cardiology", expenses: 18250 },
          { name: "Orthopedics", expenses: 15750 },
          { name: "Oncology", expenses: 12350 },
          { name: "Dermatology", expenses: 10858 },
          { name: "Psychiatry", expenses: 8750 },
          { name: "Ophthalmology", expenses: 11250 },
          { name: "Neurology", expenses: 9850 },
        ],
        expensesCategory: [
          {
            Category: "Staff Salaries",
            Amount: "$42,350",
            Total: "48%",
            lastMonth: "+3.2%",
          },
          {
            Category: "Medical Supplies",
            Amount: "$35,200",
            Total: "40%",
            lastMonth: "+2.5%",
          },
          {
            Category: "Equipment Maintenance",
            Amount: "$18,750",
            Total: "20%",
            lastMonth: "-1.8%",
          },
          {
            Category: "Utilities",
            Amount: "$15,400",
            Total: "17%",
            lastMonth: "+1.2%",
          },
          {
            Category: "Administrative",
            Amount: "$12,300",
            Total: "14%",
            lastMonth: "-0.9%",
          },
        ],
        recentTransactions: [
          {
            transactionId: "#TRX-7845",
            Date: "Today, 2:30 PM",
            Description: "Patient Payment - Emma Thompson",
            Category: "Consultation",
            Type: "Income",
            Amount: "+$150",
          },
          {
            transactionId: "#TRX-7846",
            Date: "Yesterday, 11:00 AM",
            Description: "Medical Supplies Purchase - ABC Supplies",
            Category: "Supplies",
            Type: "Insurance",
            Amount: "-$350",
          },
          {
            transactionId: "#TRX-7847",
            Date: "Last Week, 3:15 PM",
            Description: "Insurance Payment - XYZ Insurance Co.",
            Category: "Insurance",
            Type: "Expense",
            Amount: "+$1,200",
          },
          {
            transactionId: "#TRX-7848",
            Date: "Last Month, 9:45 AM",
            Description: "Utility Bill Payment - City Utilities",
            Category: "Utilities",
            Type: "Income",
            Amount: "-$200",
          },
          {
            transactionId: "#TRX-7849",
            Date: "Today, 4:00 PM",
            Description:
              "Equipment Purchase - Medical Equipment Inc. (MRI Machine)",
            Category: "Equipment",
            Type: "Expense",
            Amount: "-$25,000",
          },
          {
            transactionId: "#TRX-7850",
            Date: "Yesterday, 10:30 AM",
            Description: "Patient Payment - Liam Anderson",
            Category: "Consultation",
            Type: "Refund",
            Amount: "+$200",
          },
          {
            transactionId: "#TRX-7851",
            Date: "Last Week, 1:00 PM",
            Description: "Office Supplies Purchase - Office Depot",
            Category: "Supplies",
            Type: "Expense",
            Amount: "-$150",
          },
          {
            transactionId: "#TRX-7852",
            Date: "Last Month, 2:30 PM",
            Description: "Insurance Reimbursement - ABC Health Insurance Co.",
            Category: "Insurance",
            Type: "Income",
            Amount: "+$800",
          },
          {
            transactionId: "#TRX-7853",
            Date: "Today, 5:30 PM",
            Description: "Patient Payment - Olivia Taylor",
            Category: "Consultation",
            Type: "Income",
            Amount: "+$180",
          },
          {
            transactionId: "#TRX-7854",
            Date: "Yesterday, 12:15 PM",
            Description: "Medical Equipment Repair - XYZ Repairs",
            Category: "Equipment",
            Type: "Expense",
            Amount: "-$500",
          },
        ],
        paymentStatusPieChart: [
          { name: "Paid", value: 128450, color: "#4CAF50" },
          { name: "Pending", value: 15750, color: "#FFC107" },
          { name: "Overdue", value: 7850, color: "#F44336" },
          { name: "Refunded", value: 2350, color: "#9C27B0" },
        ],
      },
    ],
  },
  inventoryReport: {
    card: [
      {
        id: 1,
        title: "Total Items",
        value: "1,245",
        text: "+28 items since last month",
        icon: <BsBoxSeam size={24} />,
      },
      {
        id: 2,
        title: "Low Stock Items",
        value: "2.6%",
        text: "+0.8% from previous period",

        SCount: 60,

        progressColor: "#22C55E",
      },
      {
        id: 3,
        title: "Expiring Soon",
        value: "1.4%",
        text: "-0.5% from previous period",

        progressValue: 30,
        ECount: 60,
        progressColor: "#EF4444",
      },
      {
        id: 4,
        title: "Inventory Value",
        value: "248,320",
        text: "+4.3% from previous period",
        icon: <FiTruck size={24} />,
        progressValue: 20,
        progressColor: "#F59E0B",
      },
    ],
    overview: [
      {
        id: 1,
        title: "Financial Overview",
        description:
          "Monthly financial statistics including revenue, expenses, and profit.",
        revenueExpenses: [
          {
            name: "Jan",
            profit: 24050,
            expenses: 78250,
            revenue: 102300,
          },
          {
            name: "Fev",
            profit: 23800,
            expenses: 78350,
            revenue: 100150,
          },
          {
            name: "Mar",
            profit: 25800,
            expenses: 82850,
            revenue: 108650,
          },
          {
            name: "Apr",
            profit: 45125,
            expenses: 87325,
            revenue: 128450,
          },
          {
            name: "May",
            profit: 33125,
            expenses: 83200,
            revenue: 116700,
          },
          {
            name: "June",
            profit: 36400,
            expenses: 85100,
            revenue: 121500,
          },
        ],
        inventoryCategoryPieChart: [
          { name: "Medications", value: 876, color: "#8884D8" },
          { name: "Medical Supplies", value: 100, color: "#82CA9D" },
          { name: "Equipment", value: 187, color: "#FFC658" },
          { name: "Office Supplies", value: 85, color: "#FF8042" },
          { name: "Laboratory", value: 85, color: "#0088FE" },
        ],
        stockStatusPieChart: [
          { name: "In Stock", value: 1121, fill: "#4ADE80" },
          { name: "Low Stock", value: 86, fill: "#FACC15" },
          { name: "Out of Stock", value: 38, fill: "#F87171" },
        ],
        lowStock: [
          {
            itemName: "Surgical Gloves (M)",
            Category: "Medical Supplies",
            currentStock: 24,
            reorderLevel: 50,
            Supplier: "Medline Industries",
            Status: "Critical",
          },
          {
            itemName: "Syringes (10ml)",
            Category: "Medical Supplies",
            currentStock: 30,
            reorderLevel: 50,
            Supplier: "McKesson Corporation",
            Status: "Low",
          },
          {
            itemName: "IV Catheters (18G)",
            Category: "Medical Supplies",
            currentStock: 15,
            reorderLevel: 30,
            Supplier: "Cardinal Health",
            Status: "Critical",
          },
          {
            itemName: "Blood Pressure Cuffs",
            Category: "Equipment",
            currentStock: 40,
            reorderLevel: 60,
            Supplier: "Omron Healthcare",
            Status: "Low",
          },
          {
            itemName: "Thermometers (Digital)",
            Category: "Equipment",
            currentStock: 20,
            reorderLevel: 40,
            Supplier: "Philips Healthcare",
            Status: "Critical",
          },
        ],
        stockLevelTrends: [
          {
            name: "Jan",
            medications: 380,
            supplies: 320,
            equipment: 110,
            office: 190,
            laboratory: 105,
          },
          {
            name: "Fev",
            medications: 400,
            supplies: 340,
            equipment: 120,
            office: 200,
            laboratory: 110,
          },
          {
            name: "Mar",
            medications: 420,
            supplies: 360,
            equipment: 130,
            office: 210,
            laboratory: 115,
          },
          {
            name: "Apr",
            medications: 450,
            supplies: 380,
            equipment: 140,
            office: 220,
            laboratory: 120,
          },
          {
            name: "May",
            medications: 480,
            supplies: 400,
            equipment: 150,
            office: 230,
            laboratory: 125,
          },
          {
            name: "Jun",
            medications: 500,
            supplies: 420,
            equipment: 160,
            office: 240,
            laboratory: 130,
          },
        ],
        reorderFrequency: [
          { name: "weekly", expenses: 18 },
          { name: "Bi-weekly", expenses: 32 },
          { name: "monthly", expenses: 45 },
          { name: "quarterly", expenses: 25 },
          { name: "yearly", expenses: 5 },
        ],
        lowStock: [
          {
            itemName: "Surgical Gloves (M)",
            Category: "Medical Supplies",
            currentStock: 24,
            reorderLevel: 50,
            Supplier: "Medline Industries",
            Status: "Critical",
          },
          {
            itemName: "Syringes (10ml)",
            Category: "Medical Supplies",
            currentStock: 30,
            reorderLevel: 50,
            Supplier: "McKesson Corporation",
            Status: "Low",
          },
          {
            itemName: "IV Catheters (18G)",
            Category: "Medical Supplies",
            currentStock: 15,
            reorderLevel: 30,
            Supplier: "Cardinal Health",
            Status: "Critical",
          },
          {
            itemName: "Blood Pressure Cuffs",
            Category: "Equipment",
            currentStock: 40,
            reorderLevel: 60,
            Supplier: "Omron Healthcare",
            Status: "Low",
          },
          {
            itemName: "Thermometers (Digital)",
            Category: "Equipment",
            currentStock: 20,
            reorderLevel: 40,
            Supplier: "Philips Healthcare",
            Status: "Critical",
          },
        ],
        StockLevelbyCategory: [
          {
            Category: "Medications",
            totalItems: 428,
            inStock: 385,
            lowStock: 32,
            outOfStock: 11,
            stockValue: 124850,
          },
          {
            Category: "Medical Supplies",
            totalItems: 187,
            inStock: 150,
            lowStock: 20,
            outOfStock: 17,
            stockValue: 45250,
          },
          {
            Category: "Equipment",
            totalItems: 163,
            inStock: 140,
            lowStock: 15,
            outOfStock: 8,
            stockValue: 62320,
          },
          {
            Category: "Office Supplies",
            totalItems: 224,
            inStock: 200,
            lowStock: 12,
            outOfStock: 12,
            stockValue: 15200,
          },
          {
            Category: "Laboratory",
            totalItems: 228,
            inStock: 210,
            lowStock: 10,
            outOfStock: 8,
            stockValue: 12300,
          },
        ],
        monthlyUsage: [
          {
            name: "Jan",
            medications: 42,
            supplies: 35,
            equipment: 8,
            office: 22,
            laboratory: 15,
          },
          {
            name: "Fev",
            medications: 45,
            supplies: 38,
            equipment: 10,
            office: 25,
            laboratory: 18,
          },
          {
            name: "Mar",
            medications: 50,
            supplies: 40,
            equipment: 12,
            office: 28,
            laboratory: 20,
          },
          {
            name: "Apr",
            medications: 55,
            supplies: 42,
            equipment: 15,
            office: 30,
            laboratory: 22,
          },
          {
            name: "May",
            medications: 60,
            supplies: 45,
            equipment: 18,
            office: 32,
            laboratory: 25,
          },
          {
            name: "Jun",
            medications: 65,
            supplies: 48,
            equipment: 20,
            office: 35,
            laboratory: 28,
          },
        ],
        topUsedItems: [
          { name: "Surgical Gloves", usageCount: 245 },
          { name: "Syringes", usageCount: 210 },
          { name: "Gauze Pads", usageCount: 185 },
          { name: "Ibuprofen", usageCount: 165 },
          { name: "Bandages", usageCount: 140 },
        ],
        usageDepartment: [
          {
            Department: "Emergency",
            ItemsUsed: 1245,
            UsageValue: "$28,450",
            Total: "24.8%",
            Change: "3.2%",
            TopItem: "Surgical Gloves",
          },
          {
            Department: "Surgery",
            ItemsUsed: 987,
            UsageValue: "$22,300",
            Total: "19.5%",
            Change: "2.8%",
            TopItem: "Surgical Instruments",
          },
          {
            Department: "Pediatrics",
            ItemsUsed: 876,
            UsageValue: "$20,150",
            Total: "18.0%",
            Change: "1.5%",
            TopItem: "Children's Syrup",
          },
          {
            Department: "Cardiology",
            ItemsUsed: 765,
            UsageValue: "$18,200",
            Total: "16.2%",
            Change: "1.0%",
            TopItem: "Heart Monitors",
          },
          {
            Department: "Orthopedics",
            ItemsUsed: 654,
            UsageValue: "$15,750",
            Total: "14.0%",
            Change: "-0.5%",
            TopItem: "Joint Braces",
          },
        ],
        supplierDistribution: [
          { name: "Medline Industries", value: 324, color: "#8884D8" },
          { name: "McKesson", value: 286, color: "#82CA9D" },
          { name: "Cardinal Health", value: 245, color: "#FFC658" },
          { name: "Henry Schein", value: 198, color: "#FF8042" },
          { name: "Owens & Minor", value: 192, color: "#0088FE" },
        ],
        orderFulfillment: [
          {
            name: "Medline Industries",
            Time: 92.2,
            Rate: 2.4,
          },
          {
            name: "McKesson",
            Time: 96.8,
            Rate: 3.1,
          },
          {
            name: "Cardinal Health",
            Time: 97.5,
            Rate: 2.8,
          },
          {
            name: "Henry Schein",
            Time: 95.4,
            Rate: 3.5,
          },
          {
            name: "Owens & Minor",
            Time: 94.8,
            Rate: 3.8,
          },
        ],
        supplierPerformance: [
          {
            Supplier: "Medline Industries",
            "Items Supplied": 324,
            "Order Value": "$68,450",
            "Fulfillment Rate": "98.2%",
            "Avg. Delivery Time": "2.4 days",
            "Quality Rating": "4.8/5",
          },
          {
            Supplier: "McKesson",
            "Items Supplied": 286,
            "Order Value": "$62,300",
            "Fulfillment Rate": "97.5%",
            "Avg. Delivery Time": "3.1 days",
            "Quality Rating": "4.6/5",
          },
          {
            Supplier: "Cardinal Health",
            "Items Supplied": 245,
            "Order Value": "$58,200",
            "Fulfillment Rate": "96.8%",
            "Avg. Delivery Time": "2.8 days",
            "Quality Rating": "4.7/5",
          },
          {
            Supplier: "Henry Schein",
            "Items Supplied": 198,
            "Order Value": "$45,750",
            "Fulfillment Rate": "95.4%",
            "Avg. Delivery Time": "3.5 days",
            "Quality Rating": "4.5/5",
          },
          {
            Supplier: "Owens & Minor",
            "Items Supplied": 192,
            "Order Value": "$44,500",
            "Fulfillment Rate": "94.8%",
            "Avg. Delivery Time": "3.8 days",
            "Quality Rating": "4.4/5",
          },
        ],
      },
    ],
  },
  patientReport: {
    card: [
      {
        id: 1,
        title: "Total Visits",
        value: "3,842",
        text: "+12.5% from previous period",
        icon: <LuUsers size={24} />,
      },
      {
        id: 2,
        title: "New Patients",
        value: "428",
        text: "+8.2% from previous period",

        icon: <LuUserRound size={24} />,
      },
      {
        id: 3,
        title: "Avg. Visit Duration",
        value: "32 min",
        text: "-2.5 min from previous period",
        duration: 32,
      },
      {
        id: 4,
        title: "No-Show Rate",
        value: "6.8%",
        text: "-0.5% from previous period",
        rate: 6.8,
      },
    ],

    visitTypesPieChart: [
      { name: "Medications", value: 46, color: "#8884D8" },
      { name: "Medical Supplies", value: 20, color: "#82CA9D" },
      { name: "Equipment", value: 24, color: "#FFC658" },
      { name: "Office Supplies", value: 10, color: "#FF8042" },
    ],
    visitOutcomesPieChart: [
      { name: "Medications", value: 46, color: "#8884D8" },
      { name: "Medical Supplies", value: 20, color: "#82CA9D" },
      { name: "Equipment", value: 24, color: "#FFC658" },
      { name: "Office Supplies", value: 10, color: "#FF8042" },
    ],
    recentPatientVisits: [
      {
        Patient: "Sarah Johnson",
        "Visit Date": "Apr 18, 2023",
        Department: "Cardiology",
        Doctor: "Dr. Smith",
        "Visit Type": "Follow-up",
        Status: "Completed",
      },
      {
        Patient: "Michael Brown",
        "Visit Date": "Apr 20, 2023",
        Department: "Orthopedics",
        Doctor: "Dr. Johnson",
        "Visit Type": "Consultation",
        Status: "Completed",
      },
      {
        Patient: "Emma Thompson",
        "Visit Date": "Apr 22, 2023",
        Department: "Pediatrics",
        Doctor: "Dr. Emma Thompson",
        "Visit Type": "Routine Checkup",
        Status: "Completed",
      },
      {
        Patient: "Liam Anderson",
        "Visit Date": "Apr 24, 2023",
        Department: "Neurology",
        Doctor: "Dr. Asif",
        "Visit Type": "Follow-up",
        Status: "Completed",
      },
      {
        Patient: "Olivia Taylor",
        "Visit Date": "Apr 26, 2023",
        Department: "Dermatology",
        Doctor: "Dr. Rakib",
        "Visit Type": "Consultation",
        Status: "Completed",
      },
    ],
    AgeDistributionBarChart: [
      { name: "0-18", patients: 15 },
      { name: "19-35", patients: 25 },
      { name: "36-50", patients: 30 },
      { name: "51-65", patients: 20 },
      { name: "65+", patients: 10 },
    ],
    GenderDistributionPieChart: [
      { name: "Female", value: 57, color: "#0088FE" },
      { name: "Male", value: 40, color: "#00C49F" },
      { name: "Other", value: 3, color: "#FFBB28" },
    ],
    GeographicDistribution: [
      {
        Location: "Downtown",
        Patients: "	1,245",
        Total: "32.4%",
        "Avg. Visits": "2.8",
        Change: "4.2%",
      },
      {
        Location: "Uptown",
        Patients: "	987",
        Total: "25.7%",
        "Avg. Visits": "2.5",
        Change: "3.8%",
      },
      {
        Location: "Suburbs",
        Patients: "	876",
        Total: "22.8%",
        "Avg. Visits": "2.2",
        Change: "2.5%",
      },
      {
        Location: "Rural Area",
        Patients: "	654",
        Total: "17.1%",
        "Avg. Visits": "1.9",
        Change: "1.5%",
      },
      {
        Location: "Other",
        Patients: "	480",
        Total: "12.4%",
        "Avg. Visits": "1.5",
        Change: "-0.5%",
      },
    ],
    MonthlyVisitLineChart: [
      { name: "Jan", totalVisits: 220, newPatients: 45 },
      { name: "Fev", totalVisits: 250, newPatients: 50 },
      { name: "Mar", totalVisits: 300, newPatients: 60 },
      { name: "Apr", totalVisits: 350, newPatients: 70 },
      { name: "May", totalVisits: 400, newPatients: 80 },
      { name: "Jun", totalVisits: 450, newPatients: 90 },
      { name: "Jul", totalVisits: 420, newPatients: 75 },
      { name: "Aug", totalVisits: 400, newPatients: 60 },
      { name: "Sep", totalVisits: 390, newPatients: 60 },
      { name: "Oct", totalVisits: 370, newPatients: 50 },
      { name: "Nov", totalVisits: 350, newPatients: 48 },
      { name: "Dec", totalVisits: 330, newPatients: 45 },
    ],
    VisitDistributionBarChart: [
      { name: "Monday", visits: 180 },
      { name: "Tuesday", visits: 220 },
      { name: "Wednesday", visits: 250 },
      { name: "Thursday", visits: 200 },
      { name: "Friday", visits: 180 },
      { name: "Saturday", visits: 150 },
      { name: "Sunday", visits: 120 },
    ],
    visitFrequency: [
      {
        "Visit Frequency": "First-time",
        Patients: "428",
        Total: "	11.1%",
        "Avg. Duration": "30 min",
        Change: "8.2%",
      },
      {
        "Visit Frequency": "2-5 visits",
        Patients: "2,345",
        Total: "61.0%",
        "Avg. Duration": "35 min",
        Change: "5.5%",
      },
      {
        "Visit Frequency": "6-10 visits",
        Patients: "1,069",
        Total: "27.9%",
        "Avg. Duration": "28 min",
        Change: "-2.3%",
      },
      {
        "Visit Frequency": "11+ visits",
        Patients: "1,000",
        Total: "26.0%",
        "Avg. Duration": "25 min",
        Change: "-3.5%",
      },
      {
        "Visit Frequency": "No-show",
        Patients: "260",
        Total: "6.8%",
        "Avg. Duration": "20 min",
        Change: "-0.5%",
      },
    ],
  },
};
