export const mail = [
  {
    from: "dr.johnson@medixpro.com",
    to: "patient.smith@example.com",
    subject: "Your Recent Test Results",
    text: "Dear Mr. Smith, I'm pleased to inform you that your recent blood tests came back normal. No further action is needed at this time.",
    date: "2025-05-26",
    time: "10:15:00",
    isStarred: true,
    isSent: true,
    isDraft: true,
    isBin: false,
    isArchive: false,
    isImportant: false,
  },
  {
    from: "admin@medixpro.com",
    to: "dr.johnson@medixpro.com",
    subject: "Staff Meeting - April 20th",
    text: "Dear Dr. Johnson, This is a reminder about the upcoming staff meeting on April 20th at 9:00 AM in Conference Room A.",
    date: "2025-05-25",
    time: "09:30:00",
    isStarred: false,
    isSent: true,
    isDraft: true,
    isBin: false,
    isArchive: false,
    isImportant: true,
  },
  {
    from: "insurance@healthcare.com",
    to: "dr.johnson@medixpro.com",
    subject: "Claim #87654 - Additional Information Required",
    text: "We need additional documentation for claim #87654. Please provide the requested information within 14 days.",
    date: "2025-05-24",
    time: "14:45:00",
    isStarred: false,
    isSent: false,
    isDraft: false,
    isBin: false,
    isArchive: false,
    isImportant: false,
  },
  {
    from: "dr.smith@medixpro.com",
    to: "dr.johnson@medixpro.com",
    subject: "Patient Referral - Cardiology Consultation",
    text: "I'm referring Patient #54321 to you for a cardiology consultation. Patient records attached.",
    date: "2025-05-23",
    time: "07:00:00",
    isStarred: true,
    isSent: true,
    isDraft: false,
    isBin: true,
    isArchive: true,
    isImportant: true,
  },
  {
    from: "hr@medixpro.com",
    to: "dr.johnson@medixpro.com",
    subject: "Annual Leave Balance Update",
    text: "This is a reminder that you have 15 days of annual leave remaining that must be used before December 31st.",
    date: "2025-05-22",
    time: "16:10:00",
    isStarred: false,
    isSent: false,
    isDraft: false,
    isBin: false,
    isArchive: true,
    isImportant: false,
  },
  {
    from: "hr@medixpro.com",
    to: "dr.johnson@medixpro.com",
    subject: "Annual Leave Balance Update",
    text: "This is a reminder that you have 15 days of annual leave remaining that must be used before December 31st.",
    date: "2025-05-22",
    time: "16:10:00",
    isStarred: false,
    isSent: false,
    isDraft: false,
    isBin: false,
    isArchive: true,
    isImportant: false,
  },
];
