import "./globals.css";
import Header from "@/Components/Shared/Header";
import { Container } from "@/Components/UI/Container";

export const metadata = {
  title: "MedicX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
