import "./globals.css";
import Header from "@/Components/Shared/Header";
import Sidebar from "@/Components/Shared/Sidebar";
import { Container } from "@/Components/UI/Container";

export const metadata = {
  title: "MedicX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header />
          <div className="grid grid-cols-4 min-h-screen">
            <div className="col-span-1">
              <Sidebar />
            </div>

            <div className="col-span-3 p-4">{children}</div>
          </div>
        </Container>
      </body>
    </html>
  );
}
