import Header from "@/Components/Shared/Header";
import "./globals.css";

export const metadata = {
  title: "MedicX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
